env: ${ENV}
spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:trade}?connectTimeout=2000&socketTimeout=2000
    username: erueru
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    pool-name: trade-pool
    maximum-pool-size: 10
    connection-timeout: 2000
    show-sql: true
  jpa:
    ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
sentry:
  servername: ${SENTRY_SERVERNAME:local}
  dsn: ${SENTRY_DSN:}
  environment: ${ENV}
  tags:
    app.name: trade
slack:
  token: ${SLACK_TOKEN:}
logging:
  debug: ${LOGGING_DEBUG:true}
