name: ci

# PR作成時、コミットプッシュ時にワークフローを実行
on:
  pull_request:
    branches:
      - main
    types: [ opened, synchronize ]

# すべてのアクセス許可を無効に設定
permissions: { }

env:
  JAVA_VERSION: 21
  TRIVY_VERSION: 0.51.1

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      # プロジェクトのチェックアウト(ジョブ毎に実行必須)
      - name: checkout project
        # @vXのようなバージョン指定にすると、最新バージョンでセキュリティ的に問題があるアクションを意図せず使用してしまう可能性がある
        # よって@vX.Y.Zにすればリスクは軽減するが、それでもバージョンは自由に作り直せるのでより厳密にコミットハッシュを指定
        # v4.1.1 ref. https://github.com/actions/checkout/releases/tag/v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      # v4.2.1 ref. https://github.com/actions/setup-java/releases/tag/v4.2.1
      - name: install java
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      # Javaコードのフォーマットチェックを実行
      - name: run java fmt
        run: |
          ./scripts/fmt.sh

      # 既にインストール済みのTrivyがキャッシュに存在する場合restore
      - name: cache trivy CLI
        id: trivy-cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: |
            /usr/local/bin/trivy
          key: trivy-${{ env.TRIVY_VERSION }}

      # キャッシュにTrivyが存在しない場合インストール
      - name: install trivy if the cache doesn't exist
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v${{ env.TRIVY_VERSION }}

      # Trivyによるセキュリティスキャンを実行
      - name: run trivy
        run: |
          ./scripts/trivy.sh

  slack:
    if: always()
    runs-on: ubuntu-22.04
    needs: main
    permissions:
      contents: read
    steps:
      - name: checkout project
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      # ワークフローの実行結果をSlackの指定したチャネルに通知
      - name: send the workflow result to the slack channel
        uses: ./.github/actions/slack
        with:
          conclusion: ${{ needs.main.result }}
          channel_id: ${{ vars.SLACK_CHANNEL_ID }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
